name: Android Build APK

on:
  push:
    branches:
      - main # or master, depending on your default branch name
  pull_request:
    branches:
      - main # or master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Common Java version for Android
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug # This command builds the debug APK

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk
          # If your app's main module is not 'app', you might need to adjust the path here.
          # For example, if your module is named 'mymathapp', it might be: mymathapp/build/outputs/apk/debug/mymathapp-debug.apk
